### ISSUE TITLE
Multiple rate limits?

### ISSUE THREAD

**Issue by Leekao** [alltherooms/throttled-request#3]
I'm using the project to pull data from the Riot API and the rate limit is 10 requests per 10s and 500 requests per 1 min and I am having a little trouble throttling the requests to suit both limits, can you please advise me on a good way to do so?

**Comment by elhoyos** [comment]
@Leekao looks like you don't need to enforce both rate limits. The latter 8.3 req/s limit will never be reached if you enforce the 1 req/s rate limit.

**Comment by danypype** [comment]
Hello @Leekao, would you please give us some clarification on the problem? Why is there to different limits? Is that an API that throttles at a higher rate during peak time while allowing more requests at down time?

**Comment by Leekao** [comment]
@danypype no, it's nothing of the sort, it's the same rate limit but it has two rules, you can't do more than 10r every 10s and you can't do more than 500r every 10m.
@elhoyos I thought that maybe I could set both somehow to the throttling will be more efficient or something.
also a nice feature to have is to somehow set the rate increments manually, so if my script fails and reruns itself it can stick to the rate limit of the previous run.

**Comment by danypype** [comment]
@Leekao I'm afraid with the information you're providing is going to be very hard for us to help you. I'm marking this issue as closed. Please reopen it with a detailed explanation of your use case. Thank you.
