### ISSUE TITLE
support for promises libs

### ISSUE THREAD

**Issue by icaroponce** [alltherooms/throttled-request#7]
Does this lib work fine with some promise lib?

Running it with `request-promise` I got some problem. 

Only the number specified in `requests` param in `configure` method is being requested, and all the next requests are returning `undefined`.

This is what I'm doing:

```
const rp = require('request-promise');
const request = require('throttled-request')(rp);

request.configure({
  request: 2,
  milliseconds: 1000
});
```
So, if I send 10 requests, only two return correctly and the other eight return `undefined`;

**Comment by danypype** [comment]
This module does not support [`request-promise`](https://github.com/request/request-promise) as request library, only [`request`](https://github.com/request/request) is supported at the moment. If you want to have support for `request-promise`, please issue a Pull Request. Thank you.

**Comment by icaroponce** [comment]
Thank for replying,

sure, as soon as I have a free time I gonna work on it.
